# Generated by Django 4.0.6 on 2022-07-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='project-img')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('txt', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата и время публикации')),
            ],
            options={
                'verbose_name': 'Проекты',
                'verbose_name_plural': 'Наши проекты',
            },
        ),
    ]
