# Generated by Django 4.0.6 on 2022-07-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orderproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='project-img'),
        ),
        migrations.AddField(
            model_name='project',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='project-img'),
        ),
        migrations.AddField(
            model_name='project',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='project-img'),
        ),
    ]
