# Generated by Django 4.0.6 on 2022-07-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_img_1_project_img_2_project_img_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='insta',
            field=models.URLField(null=True, verbose_name='Инстаграм'),
        ),
        migrations.AddField(
            model_name='project',
            name='site',
            field=models.URLField(null=True, verbose_name='Веб сайт'),
        ),
        migrations.AddField(
            model_name='project',
            name='title2',
            field=models.TextField(max_length=30, null=True, verbose_name='Заголовок'),
        ),
    ]
