# Generated by Django 4.0.6 on 2022-07-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_insta_project_site_project_title2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Наши клиенты')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderProject',
        ),
        migrations.AlterField(
            model_name='project',
            name='title2',
            field=models.CharField(max_length=30, null=True, verbose_name='Заголовок'),
        ),
    ]
