# Generated by Django 4.0.6 on 2022-07-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_clients_delete_orderproject_alter_project_title2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Клиенты', 'verbose_name_plural': 'Наши клиенты'},
        ),
    ]
