# Generated by Django 4.0.6 on 2022-07-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_clients_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата и время'),
        ),
    ]
