# Generated by Django 4.0.6 on 2022-07-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_search_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', models.TextField(max_length=30, verbose_name='Коментарии')),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
