# Generated by Django 4.0.6 on 2022-07-12 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_comment_txt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laiks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценка',
            },
        ),
    ]
