# Generated by Django 4.1.5 on 2023-01-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_laiks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='url',
            field=models.URLField(null=True, verbose_name='URL Аддрес'),
        ),
    ]
